### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [ezechuka/EnglishWhiz#1]
May I ask what license your app is protected by? Currently, no license is declared at all, which makes it default to "all rights reserved". I assume you wanted your app being FOSS (free and open source software), but forgot to declare it such? Thanks in advance!

**Comment by ezechuka** [comment]
Thank you very much for the observation, I'll go with using MIT license.

**Comment by IzzySoft** [comment]
Wonderful, thanks! Then I'm happy to contribute :smiley:

First, your app will [become available here](https://apt.izzysoft.de/fdroid/index/apk/com.javalon.englishwhiz) in my repo around 19:00 UTC tomorrow (next sync), so it's easily accessible (incl. automated updates) for those using an [F-Droid client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181). If you wish, you can [use a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme.

Second, just a minor issue report: your app currently lacks an icon (like the `ic_launcher.png` file in  `res/mipmap*`). In launchers it will show up with the default/fallback Android icon, which might look a bit weird. The listing in my repo currently shows no icon at all, as there was no matching `*.png` found. For the latter, if you have an icon ready I can simply set that locally in an eye-blink.

Third, should you like what you see with my listing and want the metadata in [Fastlane Structure](https://gitlab.com/-/snippets/1895688) (so you have full control how your app is presented), just let me know and I can send it by PR. That could even motivate other contributors to offer translations then.

Last, a minor recommendation/suggestion: why not [tag your releases](https://github.com/ezechuka/EnglishWhiz/releases) and attach the "release APKs" to their corresponding tags? Keeps your repo slim (and leight-weighter to fork), makes the releases/APKs easier to spot – and gives you a room for "release notes" :smiley:

Thanks a lot for your fast response – and for making your app available as a tracker-free, fully offline FOSS app :heart_eyes:

**Comment by ezechuka** [comment]
Thanks for pushing my app to your repo.

App icon res added.
Created first release tag.

**Comment by ezechuka** [comment]
Okay done!
So in future releases I've to always make `versionName` match the tag name right?

**Comment by IzzySoft** [comment]
That would be great, yes. I've currently set it up with a leading `v` (which is good practice, to make sure the name is always considered to be a string) – so if one day you need a "testing tag" my updater shall not pick, simply use a different prefix (e.g. `test-1.1`) and it will be ignored.

**Comment by ezechuka** [comment]
Noted! 
Thank you.

**Comment by IzzySoft** [comment]
And the listing is online meanwhile :smiley: Thanks once more, was a joy to work with you!

**Comment by ezechuka** [comment]
Nice!
I will update the README with the F-Droid badge. Thanks!

**Comment by IzzySoft** [comment]
Thanks, looks cool :smiley:

**Comment by ezechuka** [comment]
So I committed some changes y'day & for some reason it's not updating on F-Droid. I did changed the version of the app to "1.0.0" and used "v1.1" as a release tag.
