### ISSUE TITLE
Newest to oldest sorting inside History tab

### ISSUE THREAD

**Issue by martin-desktops** [ezechuka/EnglishWhiz#3]
Hey, thanks for the app!

I find current history tab isn't very practical - right now you have to scroll down the whole history in order to back to your latest search, and I think that's the purpose of the tab in most cases. It would be better from my angle to show the recent searches on the top and the oldest at the bottom.

Regards, Martin

**Comment by ezechuka** [comment]
Thank you very much for your input, I'm going to fix that now!

**Comment by ezechuka** [comment]
Hi Martin, please confirm that the current update also fixes this issue. Thanks!

**Comment by martin-desktops** [comment]
![Screenshot_2022-05-13-07-54-21-696_com javalon englishwhiz](https://user-images.githubusercontent.com/64419373/168219964-c37db54d-7a64-4314-ba76-7303dfa0a668.jpg)

Unfortunately order of the history is still the same - latest look ups aren't on the top of list

Also the auto dark mode from screenshots doesn't apply on my device

**Comment by martin-desktops** [comment]
Thanks, I just tested the latest release and the problem seems to be solved!
