### ISSUE TITLE
Issues with displaying app icon

### ISSUE THREAD

**Issue by martin-desktops** [ezechuka/EnglishWhiz#4]
Hi,
The app icon that I am able to see on the app's page at IzzyOnDroid does not actually show up in any place in my system.

Downloaded from IzzyOnDroid
MIUI 12.5.2 Global
Android 11

Screenshot:

![Screenshot_2022-04-26-21-12-32-689_com.miui.home.jpg](https://user-images.githubusercontent.com/64419373/165374948-97c103e3-7c18-435d-b12e-07ea4db1cf9c.jpg)

**Comment by ezechuka** [comment]
Thank you very much for raising this issue, looking into it now!

**Comment by martin-desktops** [comment]
The latest build solves the problem, ty!
